# Generated by Django 5.1.2 on 2024-10-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_customername_customer_name_customer_createat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowtaken',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='cashbuy',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='cashsell',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='collectionreminder',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='lendgiven',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='matchcashbox',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='collectionreminder',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
