# Generated by Django 5.1.2 on 2024-10-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_customer_phone_alter_owner_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cash_sell',
            new_name='cashsell',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cash_buy',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='extra_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
